import { Product } from '../types';

export const CATEGORIES = [
  'Massage Therapy',
  'Hair Cut Wash & Style',
  'Nail Bar',
  'Manicure & Pedicure',
];

export const MOCK_PRODUCTS: Product[] = [
  { id: '1', name: 'Trillion Protein Transfusion', category: 'Massage Therapy', price: 3200, image: '🧴' },
  { id: '2', name: 'Calming Lavender Massage Oil', category: 'Massage Therapy', price: 2100, image: '💆‍♀️' },
  { id: '3', name: 'Deep Relaxation Aroma Therapy', category: 'Massage Therapy', price: 2800, image: '🌿' },
  { id: '4', name: 'Rose Essence Body Massage', category: 'Massage Therapy', price: 3000, image: '🌹' },
  { id: '5', name: 'Coconut Bliss Massage Cream', category: 'Massage Therapy', price: 2400, image: '🥥' },
  { id: '6', name: 'Sandalwood Body Revive Lotion', category: 'Massage Therapy', price: 2700, image: '🪵' },
  { id: '7', name: 'Aloe Calm Massage Balm', category: 'Massage Therapy', price: 2500, image: '🌱' },
  { id: '8', name: 'Ocean Mist Body Relaxation', category: 'Massage Therapy', price: 3300, image: '🌊' },
  { id: '9', name: 'Lemon Zest De-Stress Therapy', category: 'Massage Therapy', price: 2600, image: '🍋' },
  { id: '10', name: 'Herbal Infusion Massage Gel', category: 'Massage Therapy', price: 2100, image: '🌾' },
  { id: '11', name: 'Mint Cooling Body Rub', category: 'Massage Therapy', price: 2400, image: '🍃' },
  { id: '12', name: 'Tranquil Lotus Oil Therapy', category: 'Massage Therapy', price: 3000, image: '🌸' },
  { id: '13', name: 'Golden Glow Oil Fusion', category: 'Massage Therapy', price: 2900, image: '✨' },
  { id: '14', name: 'Citrus Detox Body Blend', category: 'Massage Therapy', price: 2700, image: '🍊' },
  { id: '15', name: 'Luxury Spa Essence Oil', category: 'Massage Therapy', price: 3500, image: '🕯️' },
  { id: '16', name: 'Bamboo Healing Touch Oil', category: 'Massage Therapy', price: 3100, image: '🎋' },
  { id: '17', name: 'Chamomile Comfort Balm', category: 'Massage Therapy', price: 2200, image: '🌼' },
  { id: '18', name: 'Soothing Sea Therapy Cream', category: 'Massage Therapy', price: 2800, image: '🌊' },
  { id: '19', name: 'Cocoa Butter Body Polish', category: 'Massage Therapy', price: 2500, image: '🍫' },
  { id: '20', name: 'Saffron Glow Relaxation Oil', category: 'Massage Therapy', price: 3400, image: '🧴' },

  // ✂️ Hair Cut Wash & Style (25)
  { id: '21', name: "L'Oreal Professionnel Powermix", category: 'Hair Cut Wash & Style', price: 2200, image: '💇‍♀️' },
  { id: '22', name: 'Matrix Smooth Straight Shampoo', category: 'Hair Cut Wash & Style', price: 1800, image: '🧴' },
  { id: '23', name: 'Kerastase Intense Repair Mask', category: 'Hair Cut Wash & Style', price: 3300, image: '💧' },
  { id: '24', name: 'Moroccan Argan Shampoo', category: 'Hair Cut Wash & Style', price: 2900, image: '🌰' },
  { id: '25', name: 'Suroskie My Glow All-In-One', category: 'Hair Cut Wash & Style', price: 1800, image: '💆‍♀️' },
  { id: '26', name: 'Wella Professionals Color Saver', category: 'Hair Cut Wash & Style', price: 2500, image: '🎨' },
  { id: '27', name: 'Schwarzkopf Ultimate Repair Oil', category: 'Hair Cut Wash & Style', price: 2600, image: '🛢️' },
  { id: '28', name: 'Herbal Hair Revive Serum', category: 'Hair Cut Wash & Style', price: 2000, image: '🌿' },
  { id: '29', name: 'Coconut Hydrating Shampoo', category: 'Hair Cut Wash & Style', price: 2400, image: '🥥' },
  { id: '30', name: 'L’Oreal Professional Hair Spa', category: 'Hair Cut Wash & Style', price: 3500, image: '🧴' },
  { id: '31', name: 'Keratin Infused Smooth Mist', category: 'Hair Cut Wash & Style', price: 2700, image: '💨' },
  { id: '32', name: 'Gloss & Shine Spray', category: 'Hair Cut Wash & Style', price: 2100, image: '✨' },
  { id: '33', name: 'Hydra Boost Conditioner', category: 'Hair Cut Wash & Style', price: 2600, image: '💦' },
  { id: '34', name: 'Rosemary Hair Tonic', category: 'Hair Cut Wash & Style', price: 2800, image: '🌹' },
  { id: '35', name: 'Charcoal Detox Scalp Cleanser', category: 'Hair Cut Wash & Style', price: 2200, image: '⚫' },
  { id: '36', name: 'Tea Tree Anti-Dandruff Cream', category: 'Hair Cut Wash & Style', price: 2000, image: '🌿' },
  { id: '37', name: 'Caffeine Hair Growth Booster', category: 'Hair Cut Wash & Style', price: 3100, image: '☕' },
  { id: '38', name: 'Olive Shine Conditioner', category: 'Hair Cut Wash & Style', price: 2300, image: '🫒' },
  { id: '39', name: 'Hydrating Curl Cream', category: 'Hair Cut Wash & Style', price: 2600, image: '🌀' },
  { id: '40', name: 'Silky Touch Serum', category: 'Hair Cut Wash & Style', price: 3000, image: '💫' },
  { id: '41', name: 'Gold Strength Mask', category: 'Hair Cut Wash & Style', price: 3100, image: '🥇' },
  { id: '42', name: 'Argan Glow Conditioner', category: 'Hair Cut Wash & Style', price: 2900, image: '🪞' },
  { id: '43', name: 'Coconut Milk Smooth Cream', category: 'Hair Cut Wash & Style', price: 2500, image: '🥥' },
  { id: '44', name: 'Hydra Shine Hair Mist', category: 'Hair Cut Wash & Style', price: 2700, image: '💧' },
  { id: '45', name: 'Silk Recovery Hair Mask', category: 'Hair Cut Wash & Style', price: 3300, image: '🧖‍♀️' },

  // 💅 Nail Bar (20)
  { id: '46', name: 'Suroskie Glow Foundation', category: 'Nail Bar', price: 2100, image: '✨' },
  { id: '47', name: 'Glossy Pink Nail Paint', category: 'Nail Bar', price: 1200, image: '💅' },
  { id: '48', name: 'Glitter Shine Nail Polish', category: 'Nail Bar', price: 1500, image: '🌟' },
  { id: '49', name: 'French Tip Deluxe Set', category: 'Nail Bar', price: 1900, image: '🇫🇷' },
  { id: '50', name: 'Crystal Nail Strengthener', category: 'Nail Bar', price: 1800, image: '💎' },
  { id: '51', name: 'Matte Finish Nail Coat', category: 'Nail Bar', price: 1600, image: '🖤' },
  { id: '52', name: 'Quick Dry Nail Polish', category: 'Nail Bar', price: 1300, image: '💨' },
  { id: '53', name: 'Rose Quartz Nail Color', category: 'Nail Bar', price: 1400, image: '🌸' },
  { id: '54', name: 'Ultra Gloss Top Coat', category: 'Nail Bar', price: 1600, image: '✨' },
  { id: '55', name: 'Pastel Nail Collection', category: 'Nail Bar', price: 1800, image: '🎨' },
  { id: '56', name: 'Marble Effect Nail Gel', category: 'Nail Bar', price: 2000, image: '⚪' },
  { id: '57', name: 'Chrome Finish Polish', category: 'Nail Bar', price: 2100, image: '💿' },
  { id: '58', name: 'Holographic Nail Powder', category: 'Nail Bar', price: 1900, image: '🌈' },
  { id: '59', name: 'Cuticle Nourishing Oil', category: 'Nail Bar', price: 1700, image: '💧' },
  { id: '60', name: 'Shimmer Red Nail Tint', category: 'Nail Bar', price: 1800, image: '❤️' },
  { id: '61', name: 'Longwear Nude Polish', category: 'Nail Bar', price: 1500, image: '🤎' },
  { id: '62', name: 'Golden Pearl Nail Lacquer', category: 'Nail Bar', price: 2100, image: '🌕' },
  { id: '63', name: 'Diamond Shine Top Coat', category: 'Nail Bar', price: 2000, image: '💎' },
  { id: '64', name: 'Nail Art Glitter Set', category: 'Nail Bar', price: 2300, image: '🎆' },
  { id: '65', name: 'Quick Set Nail Glue', category: 'Nail Bar', price: 1100, image: '🧴' },

  // 💖 Manicure & Pedicure (20)
  { id: '66', name: 'Rose Hand Cream', category: 'Manicure & Pedicure', price: 1700, image: '🌹' },
  { id: '67', name: 'Coconut Foot Scrub', category: 'Manicure & Pedicure', price: 1900, image: '🥥' },
  { id: '68', name: 'Mint Fresh Pedicure Gel', category: 'Manicure & Pedicure', price: 2100, image: '🍃' },
  { id: '69', name: 'Lavender Relax Hand Mask', category: 'Manicure & Pedicure', price: 2200, image: '💜' },
  { id: '70', name: 'Suroskie Hand Glow Set', category: 'Manicure & Pedicure', price: 2500, image: '✨' },
  { id: '71', name: 'Lemon Bright Hand Lotion', category: 'Manicure & Pedicure', price: 1800, image: '🍋' },
  { id: '72', name: 'Ocean Foot Soak Crystals', category: 'Manicure & Pedicure', price: 1500, image: '🌊' },
  { id: '73', name: 'Shea Butter Hand Balm', category: 'Manicure & Pedicure', price: 2000, image: '🧴' },
  { id: '74', name: 'Peppermint Foot Cream', category: 'Manicure & Pedicure', price: 2300, image: '🍃' },
  { id: '75', name: 'Vanilla Foot Polish', category: 'Manicure & Pedicure', price: 1700, image: '🍦' },
  { id: '76', name: 'Charcoal Detox Scrub', category: 'Manicure & Pedicure', price: 2000, image: '⚫' },
  { id: '77', name: 'Hydra Repair Hand Mask', category: 'Manicure & Pedicure', price: 2100, image: '💧' },
  { id: '78', name: 'Pink Clay Hand Cleanser', category: 'Manicure & Pedicure', price: 1900, image: '🌸' },
  { id: '79', name: 'Tea Tree Foot Lotion', category: 'Manicure & Pedicure', price: 1800, image: '🌿' },
  { id: '80', name: 'Citrus Fresh Foot Balm', category: 'Manicure & Pedicure', price: 2200, image: '🍊' },
  { id: '81', name: 'Gold Shine Pedicure Set', category: 'Manicure & Pedicure', price: 2400, image: '🥇' },
  { id: '82', name: 'Hydrating Hand Serum', category: 'Manicure & Pedicure', price: 2600, image: '💧' },
  { id: '83', name: 'Aloe Vera Foot Spa Cream', category: 'Manicure & Pedicure', price: 2500, image: '🌿' },
  { id: '84', name: 'Silky Smooth Foot Pack', category: 'Manicure & Pedicure', price: 2300, image: '🦶' },
  { id: '85', name: 'Sugar Glow Hand Polish', category: 'Manicure & Pedicure', price: 2000, image: '🍬' },

  // 🧴 Skin Care (25)
  { id: '86', name: 'Vitamin C Bright Serum', category: 'Skin Care', price: 3000, image: '🍊' },
  { id: '87', name: 'Hydra Boost Moisturizer', category: 'Skin Care', price: 2800, image: '💧' },
  { id: '88', name: 'Aloe Gel Soothing Cream', category: 'Skin Care', price: 2400, image: '🌿' },
  { id: '89', name: 'Night Repair Retinol Serum', category: 'Skin Care', price: 3500, image: '🌙' },
  { id: '90', name: 'Charcoal Detox Face Mask', category: 'Skin Care', price: 2200, image: '⚫' },
  { id: '91', name: 'Cucumber Cooling Gel', category: 'Skin Care', price: 2000, image: '🥒' },
  { id: '92', name: 'Honey Glow Mask', category: 'Skin Care', price: 2700, image: '🍯' },
  { id: '93', name: 'Collagen Renewal Cream', category: 'Skin Care', price: 3400, image: '🧴' },
  { id: '94', name: 'Tea Tree Spot Corrector', category: 'Skin Care', price: 2600, image: '🌿' },
  { id: '95', name: 'Papaya Brightening Face Wash', category: 'Skin Care', price: 1800, image: '🍍' },
  { id: '96', name: 'Rose Glow Toner', category: 'Skin Care', price: 2100, image: '🌹' },
  { id: '97', name: 'Caffeine Eye Serum', category: 'Skin Care', price: 2500, image: '☕' },
  { id: '98', name: 'Vitamin E Night Cream', category: 'Skin Care', price: 2300, image: '🌙' },
  { id: '99', name: 'Rice Water Face Wash', category: 'Skin Care', price: 1700, image: '🍚' },
  { id: '100', name: 'Gold Radiance Mask', category: 'Skin Care', price: 3200, image: '🥇' },
  { id: '101', name: 'SPF 50 Sun Protection Gel', category: 'Skin Care', price: 2500, image: '🌞' },
  { id: '102', name: 'AHA Exfoliating Lotion', category: 'Skin Care', price: 2600, image: '🍋' },
  { id: '103', name: 'Hydra Dew Face Cream', category: 'Skin Care', price: 2800, image: '💧' },
  { id: '104', name: 'Snail Repair Essence', category: 'Skin Care', price: 3100, image: '🐌' },
  { id: '105', name: 'Saffron Bright Glow Cream', category: 'Skin Care', price: 3400, image: '🌸' },
  { id: '106', name: 'Seaweed Detox Mask', category: 'Skin Care', price: 2700, image: '🌊' },
  { id: '107', name: 'Turmeric Clear Face Wash', category: 'Skin Care', price: 1900, image: '🧡' },
  { id: '108', name: 'Niacinamide Glow Serum', category: 'Skin Care', price: 3000, image: '💫' },
  { id: '109', name: 'Hydra Foam Cleanser', category: 'Skin Care', price: 2300, image: '🫧' },
  { id: '110', name: 'Coconut Milk Toner', category: 'Skin Care', price: 2100, image: '🥥' },
];
